channels:
  - conda-forge
  - defaults
dependencies:
  - python ==3.8.*
  - pandas=1.3.5
  - numpy=1.22.0
  - geopandas=0.10.2 
  - networkx=2.6.3  
  - osmnx=1.1
  - folium=0.12.1.post1
  - pip
  - pip:
    - pyhere